FROM maven:3.9-eclipse-temurin-21 AS dev

WORKDIR /app

# Copiamos el pom para cachear dependencias
COPY pom.xml .

# Descarga dependencias (cache)
RUN mvn dependency:go-offline -B

# El código se montará con volumes, pero dejamos esto para evitar errores
COPY src ./src

EXPOSE 8081

ENV SPRING_PROFILES_ACTIVE=dev

CMD ["mvn", "spring-boot:run"]
